[phases.setup]
nixpkgs = ["nodejs_18"]  # Adjust Node.js version if needed

[phases.install]
cmds = [
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd backend && npx prisma generate",
  "cd frontend && npm run build"
]

[phases.start]
cmds = [
  "cd backend && npm run dev &",   # Start backend in the background
  "cd frontend && npm run dev"     # Start frontend
]
